catalog_project/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.home, name='home'),
    path('category/<int:brand_id>/<int:category_id>/', views.category_detail, name='category_detail'),
]

catalog_project/catalog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('catalog.urls', namespace="catalog")),
]

catalog_project/catalog/models.py
from django.db import models

class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='categories')

    def __str__(self):
        return self.name

catalog_project/catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Brand, Category

def home(request):
    brands = Brand.objects.all()
    return render(request, 'home.html', {'brands': brands})

def category_detail(request, brand_id, category_id):
    brand = get_object_or_404(Brand, pk=brand_id)
    category = get_object_or_404(Category, brand=brand, pk=category_id)
    return render(request, 'category_detail.html', {'category': category})

catalog_project/catalog/templates/category_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ category.name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 600px;
            margin: 0;
            padding: 20px;
            box-sizing: border-box;
            background-color: #f5f5f5;
        }

        h2 {
            margin-top: 0;
            color: #333;
        }

        p {
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>{{ category.name }}:</h2>
        <p>{{ category.description }}</p>
    </div>
</body>
</html>

catalog_project/catalog/templates/home.html
<!DOCTYPE html>
<html>
<head>
<title>Каталог брендов</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h2 {
            margin-bottom: 10px;
        }

        ul {
            margin-top: 0;
            padding-left: 20px;
        }

        li {
            margin-bottom: 5px;
        }

        a {
            color: #007bff;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
<h1>Список Брендов:</h1>
    {% for brand in brands %}
    <h2>{{ brand.name }}</h2>
    <ul>
        {% for category in brand.categories.all %}
    <li><a href="{% url 'catalog:category_detail' brand_id=brand.id category_id=category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
    {% endfor %}
</body>
</html>